services:
    phpbb.akismet.listener:
        class: phpbb\akismet\event\main_listener
        arguments:
            - '@user'
            - '@request'
            - '@config'
            - '@log'
            - '@auth'
            - '@service_container'
            - '%core.php_ext%'
            - '%core.root_path%'
        tags:
            - { name: event.listener }

    phpbb.akismet.admin.controller:
        class: phpbb\akismet\controller\admin_controller
        arguments:
            - '@request'
            - '@template'
            - '@user'
            - '@log'
            - '@config'
            - '@language'
            - '@group_helper'
            - '@dbal.conn'
            - '@service_container'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%tables.groups%'

    phpbb.akismet.client.factory:
        class: phpbb\akismet\utility\akismet_factory
        arguments:
            - '@config'
            - '@log'
            - '@user'

    phpbb.akismet.client:
        class: Gothick\AkismetClient\Client
        factory_service: phpbb.akismet.client.factory
        factory_method: createAkismet

    phpbb.akismet.notification.type.post_in_queue:
        class: phpbb\akismet\notification\type\post_in_queue
        shared: false
        parent: notification.type.post_in_queue
        tags:
            - { name: notification.type }

    phpbb.akismet.notification.type.topic_in_queue:
        class: phpbb\akismet\notification\type\topic_in_queue
        shared: false
        parent: notification.type.topic_in_queue
        tags:
            - { name: notification.type }
